import json
from pathlib import Path

def generate_data_js():
    # 📁 Xác định root
    root_dir = Path(__file__).resolve().parent.parent.parent
    base_path = root_dir / 'assets/media/image'
    output_file = root_dir / 'assets/js/py.data.js'

    if not base_path.exists():
        print(f"❌ Không tìm thấy thư mục: {base_path}")
        return

    app_data = {}

    # ✔ Chỉ cần biết file là ảnh, không cần ext trong output
    valid_extensions = {'.png', '.jpg', '.jpeg', '.svg', '.webp'}

    # 📦 Lấy danh sách category (asia, europe…)
    categories = sorted([d for d in base_path.iterdir() if d.is_dir()])

    for cat_dir in categories:
        cat_key = cat_dir.name
        items = []

        # 🔍 Quét file ảnh
        files = sorted([
            f for f in cat_dir.iterdir()
            if f.is_file() and f.suffix.lower() in valid_extensions
        ])

        for file_path in files:
            file_id = file_path.stem  # tên file không có đuôi

            # 🎯 display từ id
            display_name = file_id.replace('-', ' ').title()

            items.append({
                "id": file_id,
                "display": display_name
            })

        app_data[cat_key] = items
        print(f"📦 [{cat_key}] → {len(items)} items")

    # 📝 Ghi file JS (KHÔNG ghi đè data.js)
    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("// ============================================\n")
            f.write("// AUTO GENERATED FILE - DO NOT EDIT\n")
            f.write("// Generated by gen_data.py\n")
            f.write("// ============================================\n\n")
            f.write("export const appData = ")

            json.dump(app_data, f, indent=2, ensure_ascii=False)

            f.write(";\n")

        print(f"\n✅ DONE → {output_file}")

    except Exception as e:
        print(f"❌ Lỗi ghi file: {e}")


if __name__ == "__main__":
    generate_data_js()
