const regions = {
  asia: [
    { key: "armenia", label: "Armenia" },
    { key: "azerbaijan", label: "Azerbaijan" },
    { key: "bahrain", label: "Bahrain" },
    { key: "bangladesh", label: "Bangladesh" },
    { key: "bhutan", label: "Bhutan" },
    { key: "india", label: "India" },

    { key: "brunei", label: "Brunei" },
    { key: "cambodia", label: "Cambodia" },
    { key: "china", label: "China" },
    { key: "united-arab-emirates", label: "UAE" },
    { key: "uzbekistan", label: "Uzbekistan" },
    { key: "indonesia", label: "Indonesia" },

    { key: "iran", label: "Iran" },
    { key: "iraq", label: "Iraq" },
    { key: "japan", label: "Japan" },
    { key: "jordan", label: "Jordan" },
    { key: "kuwait", label: "Kuwait" },
    { key: "kyrgyzstan", label: "Kyrgyzstan" },

    { key: "laos", label: "Laos" },
    { key: "lebanon", label: "Lebanon" },
    { key: "malaysia", label: "Malaysia" },
    { key: "maldives", label: "Maldives" },
    { key: "vietnam", label: "Vietnam" },
    { key: "myanmar", label: "Myanmar" },

    { key: "nepal", label: "Nepal" },
    { key: "north-korea", label: "North Korea" },
    { key: "oman", label: "Oman" },
    { key: "pakistan", label: "Pakistan" },
    { key: "palestine", label: "Palestine" },
    { key: "philippines", label: "Philippines" },

    { key: "qatar", label: "Qatar" },
    { key: "saudi-arabia", label: "Saudi Arabia" },
    { key: "thailand", label: "Thailand" },
    { key: "timor-leste", label: "Timor-Leste" },
    { key: "yemen", label: "Yemen" },
    { key: "hong-kong", label: "Hong Kong" }
  ],

  europe: [
    { key: "italy", label: "Italy" },
    { key: "sweden", label: "Sweden" },
    { key: "switzerland", label: "Switzerland" },
    { key: "albania", label: "Albania" },
    { key: "andorra", label: "Andorra" },
    { key: "belarus", label: "Belarus" },
    { key: "croatia", label: "Croatia" },
    { key: "luxembourg", label: "Luxembourg" },
    { key: "monaco", label: "Monaco" },
    { key: "kosovo", label: "Kosovo" },
    { key: "liechtenstein", label: "Liechtenstein" },

    { key: "ireland", label: "Ireland" },
    { key: "ukraine", label: "Ukraine" },
    { key: "united-kingdom", label: "United Kingdom" },
    { key: "macedonia", label: "North Macedonia" },
    { key: "poland", label: "Poland" },
    { key: "montenegro", label: "Montenegro" },
    { key: "portugal", label: "Portugal" },
    { key: "russia", label: "Russia" },
    { key: "romania", label: "Romania" },
    { key: "serbia", label: "Serbia" },
    { key: "slovenia", label: "Slovenia" },

    { key: "guernsey", label: "Guernsey" },
    { key: "slovakia", label: "Slovakia" },
    { key: "spain", label: "Spain" },
    { key: "denmark", label: "Denmark" },
    { key: "vatican-city", label: "Vatican City" },
    { key: "norway", label: "Norway" },
    { key: "austria", label: "Austria" },
    { key: "netherlands", label: "Netherlands" },
    { key: "belgium", label: "Belgium" },
    { key: "bulgaria", label: "Bulgaria" },
    { key: "bosnia-and-herzegovina", label: "Bosnia & Herzegovina" },

    { key: "georgia", label: "Georgia" },
    { key: "estonia", label: "Estonia" },
    { key: "finland", label: "Finland" },
    { key: "france", label: "France" },
    { key: "germany", label: "Germany" },
    { key: "greece", label: "Greece" },
    { key: "hungary", label: "Hungary" },
    { key: "iceland", label: "Iceland" },

    { key: "cyprus", label: "Cyprus" },
    { key: "san-marino", label: "San Marino" },
    { key: "czechia", label: "Czechia" },
    { key: "latvia", label: "Latvia" },
    { key: "lithuania", label: "Lithuania" },
    { key: "malta", label: "Malta" },
    { key: "moldova", label: "Moldova" }
  ]
};
